### ISSUE TITLE
1.9 - Building Bricks vs WAILA crash

### ISSUE THREAD

**Issue by christate** [hea3ven/BuildingBricks#48]
I _believe_ this triggered while I was spinning around wildly trying to shear a moving sheep, while looking up a grassy hillside in Plains-type biome, so it may also have been attempting to shear grass on/next to a grass slab or similar.

MultiMC-based mod set; single-player.

Minecraft 1.9
BuildingBricks-1.9-1.4.8
Waila-1.7.0-B2_1.9

[14:27:14] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ClientTickEvent@177b9245:
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=half, clazz=class net.minecraft.block.BlockDoublePlant$EnumBlockHalf, values=[upper, lower]} as it does not exist in BlockStateContainer{block=buildingbrickscompatvanilla:grass_slab, properties=[half, snowy]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:192) ~[ard$a.class:?]
    at net.minecraft.block.BlockDoublePlant.func_176201_c(BlockDoublePlant.java:268) ~[akw.class:?]
    at mcp.mobius.waila.addons.vanillamc.HUDHandlerVanilla.getWailaStack(HUDHandlerVanilla.java:81) ~[HUDHandlerVanilla.class:?]
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierItems(RayTracing.java:153) ~[RayTracing.class:?]
    at mcp.mobius.waila.overlay.RayTracing.getIdentifierStack(RayTracing.java:96) ~[RayTracing.class:?]
    at mcp.mobius.waila.overlay.RayTracing.getTargetStack(RayTracing.java:65) ~[RayTracing.class:?]
    at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:77) ~[WailaTickHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_59_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:336) [FMLCommonHandler.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1845) [bcf.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051) [bcf.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366) [bcf.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
[14:27:14] [Client thread/ERROR]: Index: 3 Listeners:
[14:27:14] [Client thread/ERROR]: 0: NORMAL
[14:27:14] [Client thread/ERROR]: 1: ASM: cei.ChunkEdgeRenderer@3a0b81da getKeyPress(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:27:14] [Client thread/ERROR]: 2: ASM: mezz.jei.GuiEventHandler@4e40f433 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:27:14] [Client thread/ERROR]: 3: ASM: mcp.mobius.waila.overlay.WailaTickHandler@1022091a tickClient(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:27:14] [Client thread/ERROR]: 4: ASM: journeymap.client.forge.event.StateTickHandler@2f992272 onClientTick(Lnet/minecraftforge/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[14:27:15] [Client thread/INFO]: Mapping halted in E:\Applications\MultiMC\instances\Feed The Droid 1.9\minecraft\journeymap\data\sp\Feed The Droid 1_9\DIM0
[14:27:16] [Server thread/INFO]: Stopping server

Full crash dump attached.

[crash-2016-04-14_14.27.18-client.txt](https://github.com/hea3ven/BuildingBricks/files/219998/crash-2016-04-14_14.27.18-client.txt)

**Comment by christate** [comment]
This turns out to be a game-breaking bug: it crashes on loading this world now.

[crash-2016-04-14_19.08.30-client.txt](https://github.com/hea3ven/BuildingBricks/files/220233/crash-2016-04-14_19.08.30-client.txt)

**Comment by hea3ven** [comment]
It's a waila crash that happens when you look at a tall grass that's missing the bottom part: https://bitbucket.org/ProfMobius/waila/issues/242/issue-if-double-high-flower-missing-part https://bitbucket.org/ProfMobius/waila/issues/250/crash-to-desktop-when-double-peony-flower

**Comment by christate** [comment]
Good to know; thanks!

**Comment by dannydjdk** [comment]
There still seems to be a Building Bricks bug here. If the bottom half of a plant is being destroyed by generated half slabs, but the top half isn't, shouldn't that be called a bug? The half slabs either shouldn't replace the bottom half of plants or should remove the entire plant.
And, as an added bonus, the WAILA bug would be avoided, and I can re-enable the generateGrassSlabs feature in my modpack. :)
