### ISSUE TITLE
Crashes on chunk render

### ISSUE THREAD

**Issue by Magi1053** [hea3ven/BuildingBricks#98]
```
java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class biomesoplenty.api.enums.BOPPlants, values=[shortgrass, mediumgrass, bush, sprout, poisonivy, berrybush, shrub, wheatgrass, dampgrass, koru, cloverpatch, leafpile, deadleafpile, deadgrass, desertgrass, desertsprouts]} as it does not exist in BlockStateContainer{block=minecraft:grass, properties=[snowy]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
	at biomesoplenty.common.block.BlockBOPPlant.func_176200_f(BlockBOPPlant.java:287)
	at com.hea3ven.buildingbricks.compat.vanilla.GrassSlabWorldGen.onPopulateChunkPreEvent(GrassSlabWorldGen.java:95)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_100_GrassSlabWorldGen_onPopulateChunkPreEvent_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:635)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:591)
	at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:194)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
	at net.minecraft.server.management.PlayerChunkMapEntry.redirect$onProvidePlayerChunk$zom000(PlayerChunkMapEntry.java:1079)
	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```

Full crash report: http://pastebin.com/b0gG6MKe

**Comment by Magi1053** [comment]
bump
